# Generated by Django 5.1.15 on 2026-03-31 07:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("序号", models.IntegerField(verbose_name="序号")),
                ("分公司", models.CharField(max_length=100, verbose_name="分公司")),
                (
                    "分公司编号",
                    models.CharField(max_length=50, verbose_name="分公司编号"),
                ),
                (
                    "资产编号",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="资产编号"
                    ),
                ),
                ("资产类目", models.CharField(max_length=100, verbose_name="资产类目")),
                ("物品分类", models.CharField(max_length=100, verbose_name="物品分类")),
                ("资产名称", models.CharField(max_length=200, verbose_name="资产名称")),
                (
                    "规格",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="规格"
                    ),
                ),
                (
                    "供应商",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="供应商"
                    ),
                ),
                (
                    "图片",
                    models.ImageField(
                        blank=True, null=True, upload_to="assets/", verbose_name="图片"
                    ),
                ),
                (
                    "入库日期",
                    models.DateField(blank=True, null=True, verbose_name="入库日期"),
                ),
                (
                    "是否租用",
                    models.BooleanField(default=False, verbose_name="是否租用"),
                ),
                ("数量", models.IntegerField(default=1, verbose_name="数量")),
                (
                    "单价",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="单价",
                    ),
                ),
                (
                    "购入金额",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="购入金额",
                    ),
                ),
                (
                    "出库日期",
                    models.DateField(blank=True, null=True, verbose_name="出库日期"),
                ),
                (
                    "所属部门",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="所属部门"
                    ),
                ),
                (
                    "使用人",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="使用人"
                    ),
                ),
                (
                    "当前状态",
                    models.CharField(
                        choices=[
                            ("在库", "在库"),
                            ("使用中", "使用中"),
                            ("维修中", "维修中"),
                            ("报废", "报废"),
                        ],
                        default="在库",
                        max_length=20,
                        verbose_name="当前状态",
                    ),
                ),
                (
                    "警戒线",
                    models.IntegerField(blank=True, null=True, verbose_name="警戒线"),
                ),
                (
                    "是否充足",
                    models.BooleanField(default=True, verbose_name="是否充足"),
                ),
                (
                    "电脑序列号",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="电脑序列号",
                    ),
                ),
                ("备注", models.TextField(blank=True, default="", verbose_name="备注")),
            ],
            options={
                "verbose_name": "资产",
                "verbose_name_plural": "资产",
                "db_table": "assets_asset",
                "ordering": ["-序号"],
            },
        ),
    ]
