# Generated by Django 5.1.15 on 2026-04-16 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0001_initial"),
        ("organizations", "0003_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assets",
                to="organizations.branch",
                verbose_name="所属分公司",
            ),
        ),
    ]
