# Generated by Django 5.1.15 on 2026-04-24 06:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0003_populate_branch_fk"),
        ("organizations", "0004_add_fixedasset_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="FixedAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "内部编号",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="内部编号"
                    ),
                ),
                ("资产编号", models.CharField(max_length=100, verbose_name="资产编号")),
                (
                    "资产名称",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="资产名称"
                    ),
                ),
                (
                    "序列号",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="序列号"
                    ),
                ),
                (
                    "供应商",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="供应商"
                    ),
                ),
                (
                    "使用人",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="使用人"
                    ),
                ),
                (
                    "所属部门",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="所属部门"
                    ),
                ),
                (
                    "当前状态",
                    models.CharField(
                        choices=[("在库", "在库"), ("在用", "在用"), ("空闲", "空闲")],
                        default="在库",
                        max_length=20,
                        verbose_name="当前状态",
                    ),
                ),
                (
                    "分公司",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="分公司"
                    ),
                ),
                (
                    "分公司编号",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="分公司编号"
                    ),
                ),
                (
                    "入库日期",
                    models.DateField(blank=True, null=True, verbose_name="入库日期"),
                ),
                ("备注", models.TextField(blank=True, default="", verbose_name="备注")),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instances",
                        to="assets.asset",
                        verbose_name="所属品目",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fixed_assets",
                        to="organizations.branch",
                        verbose_name="所属分公司",
                    ),
                ),
            ],
            options={
                "verbose_name": "固定资产实例",
                "verbose_name_plural": "固定资产实例",
                "db_table": "assets_fixedasset",
                "ordering": ["内部编号"],
            },
        ),
    ]
