# Generated by Django 5.1.15 on 2026-06-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0004_add_fixedasset_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="入库日期",
            field=models.DateField(
                blank=True, db_index=True, null=True, verbose_name="入库日期"
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="分公司编号",
            field=models.CharField(
                db_index=True, max_length=50, verbose_name="分公司编号"
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="当前状态",
            field=models.CharField(
                choices=[
                    ("在库", "在库"),
                    ("使用中", "使用中"),
                    ("维修中", "维修中"),
                    ("报废", "报废"),
                ],
                db_index=True,
                default="在库",
                max_length=20,
                verbose_name="当前状态",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="资产类目",
            field=models.CharField(
                db_index=True, max_length=100, verbose_name="资产类目"
            ),
        ),
    ]
