# Generated by Django 5.1.15 on 2026-07-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "assets",
            "0005_alter_asset_入库日期_alter_asset_分公司编号_alter_asset_当前状态_and_more",
        ),
        ("organizations", "0004_add_fixedasset_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="fixedasset",
            name="出库日期",
            field=models.DateField(blank=True, null=True, verbose_name="出库日期"),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="单价",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="单价",
            ),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="数量",
            field=models.IntegerField(default=1, verbose_name="数量"),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="是否租用",
            field=models.BooleanField(default=False, verbose_name="是否租用"),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="物品分类",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="物品分类"
            ),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="规格",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="规格"
            ),
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="购入金额",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                verbose_name="购入金额",
            ),
        ),
        migrations.AddConstraint(
            model_name="fixedasset",
            constraint=models.UniqueConstraint(
                condition=models.Q(("序列号", ""), _negated=True),
                fields=("分公司", "序列号"),
                name="unique_branch_serial",
            ),
        ),
    ]
