# Generated by Django 5.1.15 on 2026-07-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0006_fixedasset_出库日期_fixedasset_单价_fixedasset_数量_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fixedasset",
            name="asset",
        ),
        migrations.AddField(
            model_name="fixedasset",
            name="资产类目",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="资产类目"
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="资产编号",
            field=models.CharField(
                db_index=True, max_length=100, verbose_name="资产编号"
            ),
        ),
    ]
