# Generated by Django 5.1.15 on 2026-07-16 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0007_remove_fixedasset_asset_fixedasset_资产类目_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="fixedasset",
            name="unique_branch_serial",
        ),
    ]
