# Generated by Django 5.1.15 on 2026-08-19 01:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


def seed_asset_stock_from_assets(apps, schema_editor):
    """按现有资产明细聚合（分公司+资产编号）生成台账初始行。

    纯 Python 内存聚合：不用 SQL 聚合取"组内首行"（id 为 UUID，
    PostgreSQL 无 min(uuid) 聚合函数，SQLite 有——曾导致生产迁移失败）。
    """
    Asset = apps.get_model("assets", "Asset")
    AssetStock = apps.get_model("assets", "AssetStock")
    Branch = apps.get_model("organizations", "Branch")

    branch_id_by_name = {}
    grouped = {}  # (分公司, 资产编号) -> {"first": 首行, "总数量": int, "警戒线max": int|None}

    # 按序号升序遍历，保证"首行"确定性（序号最小的明细行）
    for asset in Asset.objects.order_by("序号", "created_at").iterator():
        key = (asset.分公司, asset.资产编号)
        g = grouped.get(key)
        if g is None:
            g = {"first": asset, "总数量": 0, "警戒线max": None}
            grouped[key] = g
        g["总数量"] += asset.数量 or 0
        warn = asset.警戒线
        if warn is not None and (g["警戒线max"] is None or warn > g["警戒线max"]):
            g["警戒线max"] = warn

    for (分公司, 资产编号), g in grouped.items():
        first = g["first"]
        branch_id = first.branch_id
        if not branch_id and 分公司:
            # 兜底：明细行 branch FK 缺失时按分公司名解析
            if 分公司 not in branch_id_by_name:
                branch_id_by_name[分公司] = Branch.objects.filter(
                    name=分公司,
                ).values_list("id", flat=True).first()
            branch_id = branch_id_by_name.get(分公司)
        警戒线 = g["警戒线max"]
        数量 = g["总数量"]
        AssetStock.objects.create(
            分公司=分公司,
            分公司编号=first.分公司编号 or "",
            branch_id=branch_id,
            资产编号=资产编号,
            资产类目=first.资产类目 or "",
            物品分类=first.物品分类 or "",
            资产名称=first.资产名称 or "",
            规格=first.规格 or "",
            数量=数量,
            警戒线=警戒线,
            是否充足=(警戒线 is None) or (数量 >= 警戒线),
        )


def unseed_asset_stock(apps, schema_editor):
    AssetStock = apps.get_model("assets", "AssetStock")
    AssetStock.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0011_backfill_fixedasset_branch_fk_again"),
        ("organizations", "0006_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetStock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("分公司", models.CharField(max_length=100, verbose_name="分公司")),
                (
                    "分公司编号",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="分公司编号"
                    ),
                ),
                (
                    "资产编号",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="资产编号"
                    ),
                ),
                (
                    "资产类目",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="资产类目"
                    ),
                ),
                (
                    "物品分类",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="物品分类"
                    ),
                ),
                (
                    "资产名称",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="资产名称"
                    ),
                ),
                (
                    "规格",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="规格"
                    ),
                ),
                ("数量", models.IntegerField(default=0, verbose_name="数量")),
                (
                    "警戒线",
                    models.IntegerField(blank=True, null=True, verbose_name="警戒线"),
                ),
                (
                    "是否充足",
                    models.BooleanField(default=True, verbose_name="是否充足"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_stocks",
                        to="organizations.branch",
                        verbose_name="所属分公司",
                    ),
                ),
            ],
            options={
                "verbose_name": "资产汇总台账",
                "verbose_name_plural": "资产汇总台账",
                "db_table": "assets_assetstock",
                "ordering": ["分公司", "资产编号"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("分公司", "资产编号"),
                        name="unique_summary_branch_asset_code",
                    )
                ],
            },
        ),
        migrations.RunPython(seed_asset_stock_from_assets, unseed_asset_stock),
    ]
