# Generated by Django 5.1.15 on 2026-08-19 01:58

import django.db.models.deletion
import uuid
from django.db import migrations, models
from django.db.models import Sum, Max, Min


def seed_asset_stock_from_assets(apps, schema_editor):
    """按现有资产明细聚合（分公司+资产编号）生成台账初始行。"""
    Asset = apps.get_model("assets", "Asset")
    AssetStock = apps.get_model("assets", "AssetStock")

    grouped = Asset.objects.values("分公司", "资产编号").annotate(
        总数量=Sum("数量"), 警戒线max=Max("警戒线"), 首行id=Min("id"),
    )
    first_ids = [g["首行id"] for g in grouped]
    first_map = {a.id: a for a in Asset.objects.filter(id__in=first_ids)}

    for g in grouped:
        first = first_map.get(g["首行id"])
        if first is None:
            continue
        branch_id = first.branch_id
        if not branch_id and g["分公司"]:
            # 兜底：明细行 branch FK 缺失时按分公司名解析
            Branch = apps.get_model("organizations", "Branch")
            matched = Branch.objects.filter(name=g["分公司"]).first()
            branch_id = matched.id if matched else None
        警戒线 = g["警戒线max"]
        数量 = g["总数量"] or 0
        AssetStock.objects.create(
            分公司=g["分公司"],
            分公司编号=first.分公司编号 or "",
            branch_id=branch_id,
            资产编号=g["资产编号"],
            资产类目=first.资产类目 or "",
            物品分类=first.物品分类 or "",
            资产名称=first.资产名称 or "",
            规格=first.规格 or "",
            数量=数量,
            警戒线=警戒线,
            是否充足=(警戒线 is None) or (数量 >= 警戒线),
        )


def unseed_asset_stock(apps, schema_editor):
    AssetStock = apps.get_model("assets", "AssetStock")
    AssetStock.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0011_backfill_fixedasset_branch_fk_again"),
        ("organizations", "0006_company"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetStock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("分公司", models.CharField(max_length=100, verbose_name="分公司")),
                (
                    "分公司编号",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="分公司编号"
                    ),
                ),
                (
                    "资产编号",
                    models.CharField(
                        db_index=True, max_length=100, verbose_name="资产编号"
                    ),
                ),
                (
                    "资产类目",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="资产类目"
                    ),
                ),
                (
                    "物品分类",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="物品分类"
                    ),
                ),
                (
                    "资产名称",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="资产名称"
                    ),
                ),
                (
                    "规格",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="规格"
                    ),
                ),
                ("数量", models.IntegerField(default=0, verbose_name="数量")),
                (
                    "警戒线",
                    models.IntegerField(blank=True, null=True, verbose_name="警戒线"),
                ),
                (
                    "是否充足",
                    models.BooleanField(default=True, verbose_name="是否充足"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asset_stocks",
                        to="organizations.branch",
                        verbose_name="所属分公司",
                    ),
                ),
            ],
            options={
                "verbose_name": "资产汇总台账",
                "verbose_name_plural": "资产汇总台账",
                "db_table": "assets_assetstock",
                "ordering": ["分公司", "资产编号"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("分公司", "资产编号"),
                        name="unique_summary_branch_asset_code",
                    )
                ],
            },
        ),
        migrations.RunPython(seed_asset_stock_from_assets, unseed_asset_stock),
    ]
