# Generated by Django 5.1.15 on 2026-08-23 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0013_assetstock_v2_restructure"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assetstock",
            options={
                "ordering": ["branch__name", "item__asset_code"],
                "verbose_name": "资产汇总台账",
                "verbose_name_plural": "资产汇总台账",
            },
        ),
    ]
