# Generated by Django 5.1.15 on 2026-08-23 11:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0014_alter_assetstock_options"),
        ("categories", "0004_remove_category_asset_count_and_more"),
        ("organizations", "0007_branch_team_single_parent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LedgerAdjustment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "目标列",
                    models.CharField(
                        choices=[
                            ("在库数量", "在库"),
                            ("在用数量", "在用"),
                            ("回收库数量", "回收库"),
                        ],
                        max_length=20,
                        verbose_name="目标列",
                    ),
                ),
                ("变动量", models.IntegerField(verbose_name="变动量（可正可负）")),
                ("事由", models.CharField(max_length=200, verbose_name="事由")),
                (
                    "is_initial",
                    models.BooleanField(default=False, verbose_name="期初单"),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_adjustments",
                        to="organizations.branch",
                        verbose_name="分公司",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_adjustments",
                        to="categories.category",
                        verbose_name="品目",
                    ),
                ),
                (
                    "经办人",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_adjustments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="经办人",
                    ),
                ),
            ],
            options={
                "verbose_name": "台账调整单",
                "verbose_name_plural": "台账调整单",
                "db_table": "assets_ledger_adjustment",
                "ordering": ["-created_at"],
            },
        ),
    ]
