# Generated by Django 5.1.15 on 2026-08-24 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0020_retire_asset"),
        ("inventories", "0006_drop_inventory_asset_fk"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ledgeradjustment",
            options={
                "ordering": ["-单据编号", "-created_at"],
                "verbose_name": "台账调整单",
                "verbose_name_plural": "台账调整单",
            },
        ),
        migrations.AddField(
            model_name="ledgeradjustment",
            name="source_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="adjustments",
                to="inventories.inventorytask",
                verbose_name="来源盘点任务",
            ),
        ),
        migrations.AddField(
            model_name="ledgeradjustment",
            name="单据编号",
            field=models.CharField(
                blank=True,
                db_index=True,
                max_length=32,
                null=True,
                unique=True,
                verbose_name="单据编号",
            ),
        ),
    ]
