# Generated by Django 5.1.15 on 2026-09-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0022_backfill_adjustment_doc_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="fixedasset",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="fixed_assets/",
                verbose_name="物品图片",
            ),
        ),
    ]
