# Generated by Django 5.1.15 on 2026-09-18 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0027_fixedasset_spec"),
    ]

    operations = [
        migrations.AddField(
            model_name="fixedasset",
            name="采购日期",
            field=models.DateField(
                blank=True, null=True, verbose_name="采购日期（个体覆盖，空=批次口径）"
            ),
        ),
    ]
