# Generated by Django 5.1.15 on 2026-09-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    # 仅依赖本 app 前序即可（branch/序列号 列在早期迁移已建、FK 依赖经本 app
    # 历史迁移传递可见）。makemigrations 自动附加的跨 app 依赖边
    # （organizations.0009 等）会改变测试建库时该迁移 RunPython 的状态渲染
    # 上下文致 LookupError，故裁剪。
    dependencies = [
        ("assets", "0028_fixedasset_purchase_date"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="fixedasset",
            constraint=models.UniqueConstraint(
                condition=models.Q(("序列号", ""), _negated=True),
                fields=("branch", "序列号"),
                name="unique_branch_serial",
            ),
        ),
    ]
