# Generated by Django 5.1.15 on 2026-03-31 07:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asset_category",
                    models.CharField(max_length=100, verbose_name="资产类目"),
                ),
                (
                    "item_category",
                    models.CharField(max_length=100, verbose_name="物品分类"),
                ),
                (
                    "asset_name",
                    models.CharField(max_length=200, verbose_name="资产名称"),
                ),
                (
                    "asset_code",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="资产编号"
                    ),
                ),
                ("unit", models.CharField(max_length=20, verbose_name="计量单位")),
                (
                    "warning_line",
                    models.IntegerField(blank=True, null=True, verbose_name="警戒线"),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
                (
                    "asset_count",
                    models.IntegerField(default=0, verbose_name="资产数量"),
                ),
                (
                    "in_stock_count",
                    models.IntegerField(default=0, verbose_name="在库数量"),
                ),
            ],
            options={
                "verbose_name": "资产类目",
                "verbose_name_plural": "资产类目",
                "db_table": "categories_category",
                "ordering": ["asset_code"],
            },
        ),
    ]
