# Generated by Django 5.1.15 on 2026-04-09 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="attribute_template",
            field=models.JSONField(blank=True, default=dict, verbose_name="属性模板"),
        ),
        migrations.AlterField(
            model_name="category",
            name="asset_code",
            field=models.CharField(
                error_messages={"unique": "资产编号已存在，请使用其他编号"},
                max_length=100,
                unique=True,
                verbose_name="资产编号",
            ),
        ),
    ]
