# Generated by Django 5.1.15 on 2026-04-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0002_category_attribute_template_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="asset_total_quantity",
            field=models.IntegerField(default=0, verbose_name="资产总数量"),
        ),
        migrations.AddField(
            model_name="category",
            name="in_stock_quantity",
            field=models.IntegerField(default=0, verbose_name="在库总数量"),
        ),
    ]
