# Generated by Django 5.1.15 on 2026-08-23 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0003_add_quantity_fields_to_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="asset_count",
        ),
        migrations.RemoveField(
            model_name="category",
            name="asset_total_quantity",
        ),
        migrations.RemoveField(
            model_name="category",
            name="in_stock_count",
        ),
        migrations.RemoveField(
            model_name="category",
            name="in_stock_quantity",
        ),
        migrations.AddField(
            model_name="category",
            name="default_supplier",
            field=models.CharField(
                blank=True,
                default="",
                max_length=200,
                verbose_name="默认供应商（仅预填）",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="categories/", verbose_name="图片"
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="is_rental",
            field=models.BooleanField(default=False, verbose_name="是否租用"),
        ),
        migrations.AddField(
            model_name="category",
            name="management_type",
            field=models.CharField(
                choices=[("quantity", "数量管理"), ("instance", "实例管理")],
                default="quantity",
                max_length=20,
                verbose_name="管理方式",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="specification",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="规格（定义性）"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="warning_line",
            field=models.IntegerField(blank=True, null=True, verbose_name="默认警戒线"),
        ),
    ]
