# Generated by Django 5.1.15 on 2026-08-27 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0004_remove_category_asset_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="management_type",
            field=models.CharField(
                choices=[
                    ("quantity", "数量管理"),
                    ("instance", "实例管理"),
                    ("consumable", "消耗品"),
                ],
                default="quantity",
                max_length=20,
                verbose_name="管理方式",
            ),
        ),
    ]
