# Generated by Django 5.1.15 on 2026-04-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="system_avatar",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="系统预设头像标识"
            ),
        ),
    ]
