# Generated by Django 5.1.15 on 2026-06-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_system_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "admin"),
                    ("director", "director"),
                    ("manager", "manager"),
                    ("supervisor", "supervisor"),
                    ("leader", "leader"),
                    ("staff", "staff"),
                ],
                default="staff",
                max_length=20,
            ),
        ),
    ]
