# Generated by Django 5.1.15 on 2026-08-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_drop_flat_org_fks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "admin"),
                    ("director", "director"),
                    ("manager", "manager"),
                    ("leader", "leader"),
                    ("staff", "staff"),
                ],
                default="staff",
                max_length=20,
            ),
        ),
    ]
