# Generated by Django 5.1.15 on 2026-08-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "admin"),
                    ("director", "director"),
                    ("manager", "manager"),
                    ("leader", "leader"),
                ],
                default="manager",
                max_length=20,
            ),
        ),
    ]
