# Generated by Django 5.1.15 on 2026-04-01 02:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="操作人姓名"
                    ),
                ),
                (
                    "user_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="操作人手机"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("login", "登录"),
                            ("logout", "登出"),
                            ("create", "创建"),
                            ("update", "更新"),
                            ("delete", "删除"),
                            ("approve", "审批通过"),
                            ("reject", "审批驳回"),
                            ("export", "导出"),
                            ("import", "导入"),
                            ("view", "查看"),
                        ],
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(max_length=50, verbose_name="资源类型"),
                ),
                (
                    "resource_id",
                    models.UUIDField(blank=True, null=True, verbose_name="资源ID"),
                ),
                (
                    "resource_name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="资源名称"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="操作描述")),
                (
                    "before_data",
                    models.JSONField(blank=True, null=True, verbose_name="变更前数据"),
                ),
                (
                    "after_data",
                    models.JSONField(blank=True, null=True, verbose_name="变更后数据"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="用户代理"
                    ),
                ),
                (
                    "request_path",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="请求路径"
                    ),
                ),
                (
                    "request_method",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="请求方法"
                    ),
                ),
                (
                    "is_success",
                    models.BooleanField(default=True, verbose_name="是否成功"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="错误信息"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
            ],
            options={
                "verbose_name": "审计日志",
                "verbose_name_plural": "审计日志",
                "db_table": "audit_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="audit_log_user_id_b57afc_idx",
                    ),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="audit_log_resourc_2570dd_idx",
                    ),
                    models.Index(
                        fields=["action", "-created_at"],
                        name="audit_log_action_7c9e02_idx",
                    ),
                ],
            },
        ),
    ]
