# Generated by Django 5.1.15 on 2026-09-22 03:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="供应商名称"
                    ),
                ),
                (
                    "联系人",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="联系人"
                    ),
                ),
                (
                    "电话",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="电话"
                    ),
                ),
            ],
            options={
                "verbose_name": "供应商",
                "verbose_name_plural": "供应商字典",
                "db_table": "suppliers_supplier",
                "ordering": ["name"],
            },
        ),
    ]
