# Generated by Django 5.1.15 on 2026-03-31 07:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "expected_qty",
                    models.IntegerField(default=0, verbose_name="应盘数量"),
                ),
                (
                    "actual_qty",
                    models.IntegerField(blank=True, null=True, verbose_name="实盘数量"),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("matched", "正常"),
                            ("surplus", "盘盈"),
                            ("missing", "盘亏"),
                            ("unchecked", "未盘点"),
                        ],
                        default="unchecked",
                        max_length=20,
                        verbose_name="盘点结果",
                    ),
                ),
                (
                    "check_count",
                    models.IntegerField(default=0, verbose_name="盘点次数"),
                ),
                (
                    "checked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="盘点时间"
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
            ],
            options={
                "verbose_name": "盘点项",
                "verbose_name_plural": "盘点项",
                "db_table": "inventories_item",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, verbose_name="任务名称")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待盘点"),
                            ("in_progress", "盘点中"),
                            ("pending_review", "待审核"),
                            ("completed", "已完成"),
                            ("rejected", "已驳回"),
                            ("cancelled", "已作废"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "missed_rule",
                    models.CharField(
                        choices=[("keep", "保持不变"), ("zero", "清零处理")],
                        default="keep",
                        max_length=20,
                        verbose_name="漏盘规则",
                    ),
                ),
                (
                    "repeat_rule",
                    models.CharField(
                        choices=[
                            ("last", "以最后一次为准"),
                            ("accumulate", "累计数量"),
                        ],
                        default="last",
                        max_length=20,
                        verbose_name="重复盘点规则",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="提交时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="驳回时间"
                    ),
                ),
                (
                    "reject_reason",
                    models.TextField(blank=True, default="", verbose_name="驳回原因"),
                ),
            ],
            options={
                "verbose_name": "盘点任务",
                "verbose_name_plural": "盘点任务",
                "db_table": "inventories_task",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryCheck",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("qty", models.IntegerField(verbose_name="盘点数量")),
                (
                    "checked_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="盘点时间"),
                ),
                (
                    "device",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="设备信息"
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_checks",
                        to="assets.asset",
                        verbose_name="资产",
                    ),
                ),
            ],
            options={
                "verbose_name": "盘点记录",
                "verbose_name_plural": "盘点记录",
                "db_table": "inventories_check",
                "ordering": ["-checked_at"],
            },
        ),
    ]
