# Generated by Django 5.1.15 on 2026-03-31 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assets", "0001_initial"),
        ("categories", "0001_initial"),
        ("inventories", "0001_initial"),
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorycheck",
            name="checked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_checks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="盘点人",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="inventory_items",
                to="assets.asset",
                verbose_name="资产",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="checked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checked_items",
                to=settings.AUTH_USER_MODEL,
                verbose_name="盘点人",
            ),
        ),
        migrations.AddField(
            model_name="inventorycheck",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="check_records",
                to="inventories.inventoryitem",
                verbose_name="盘点项",
            ),
        ),
        migrations.AddField(
            model_name="inventorytask",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_tasks",
                to="organizations.branch",
                verbose_name="盘点分公司",
            ),
        ),
        migrations.AddField(
            model_name="inventorytask",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_tasks",
                to="categories.category",
                verbose_name="资产类目",
            ),
        ),
        migrations.AddField(
            model_name="inventorytask",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_inventory_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建人",
            ),
        ),
        migrations.AddField(
            model_name="inventorytask",
            name="rejected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rejected_inventory_tasks",
                to=settings.AUTH_USER_MODEL,
                verbose_name="驳回人",
            ),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="inventories.inventorytask",
                verbose_name="盘点任务",
            ),
        ),
        migrations.AddField(
            model_name="inventorycheck",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checks",
                to="inventories.inventorytask",
                verbose_name="盘点任务",
            ),
        ),
    ]
