# Generated by Django 5.1.15 on 2026-06-28 10:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0003_add_quantity_fields_to_category"),
        ("inventories", "0002_initial"),
        ("organizations", "0004_add_fixedasset_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="inventorytask",
            index=models.Index(
                fields=["branch", "status"], name="inventories_task_branch_status"
            ),
        ),
    ]
