# Generated by Django 5.1.15 on 2026-08-27 09:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0022_backfill_adjustment_doc_no"),
        ("inventories", "0006_drop_inventory_asset_fk"),
        ("organizations", "0008_department"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inventorytask",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inventory_tasks",
                to="organizations.department",
                verbose_name="盘点部门（实例盘）",
            ),
        ),
        migrations.AddField(
            model_name="inventorytask",
            name="stock_bin",
            field=models.CharField(
                choices=[("stock", "在库"), ("recycle", "回收库")],
                default="stock",
                max_length=20,
                verbose_name="库别",
            ),
        ),
        migrations.CreateModel(
            name="InventoryInstanceItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("matched", "已找到"),
                            ("missing", "未找到"),
                            ("unchecked", "未核对"),
                        ],
                        default="unchecked",
                        max_length=20,
                        verbose_name="核对结果",
                    ),
                ),
                (
                    "check_count",
                    models.IntegerField(default=0, verbose_name="核对次数"),
                ),
                (
                    "checked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="核对时间"
                    ),
                ),
                (
                    "remarks",
                    models.TextField(blank=True, default="", verbose_name="备注"),
                ),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checked_instance_items",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="核对人",
                    ),
                ),
                (
                    "instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_items",
                        to="assets.fixedasset",
                        verbose_name="实例",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="instance_items",
                        to="inventories.inventorytask",
                        verbose_name="盘点任务",
                    ),
                ),
            ],
            options={
                "verbose_name": "实例盘项",
                "verbose_name_plural": "实例盘项",
                "db_table": "inventories_instance_item",
                "ordering": ["instance__内部编号"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("task", "instance"), name="uniq_inventory_task_instance"
                    )
                ],
            },
        ),
    ]
