# Generated by Django 5.1.15 on 2026-06-25 06:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0004_add_fixedasset_model"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagementScope",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoped_users",
                        to="organizations.branch",
                        verbose_name="授权分公司",
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoped_users",
                        to="organizations.region",
                        verbose_name="授权大区",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoped_users",
                        to="organizations.team",
                        verbose_name="授权行政组",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="management_scopes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="被授权员工",
                    ),
                ),
            ],
            options={
                "verbose_name": "管理授权（组织节点）",
                "verbose_name_plural": "管理授权（组织节点）",
                "db_table": "permissions_management_scope",
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("branch__isnull", True),
                                ("region__isnull", True),
                                ("team__isnull", False),
                            ),
                            models.Q(
                                ("branch__isnull", False),
                                ("region__isnull", True),
                                ("team__isnull", True),
                            ),
                            models.Q(
                                ("branch__isnull", True),
                                ("region__isnull", False),
                                ("team__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="exactly_one_org_node",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("region__isnull", False)),
                        fields=("user", "region"),
                        name="uniq_user_region",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("branch__isnull", False)),
                        fields=("user", "branch"),
                        name="uniq_user_branch",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("team__isnull", False)),
                        fields=("user", "team"),
                        name="uniq_user_team",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OperationGrant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("manage_users", "管理用户"),
                            ("manage_organizations", "管理组织架构"),
                            ("manage_categories", "管理资产分类"),
                            ("manage_assets", "管理资产（增删改/导入）"),
                            ("approve_transfer", "审批资产流转"),
                            ("approve_inventory", "审批盘点任务"),
                            ("view_audit", "查看审计日志"),
                            ("view_all_notifications", "查看抄送记录"),
                            ("view_reports", "查看统计报表"),
                        ],
                        max_length=50,
                        verbose_name="业务操作",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operation_grants",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="被授权员工",
                    ),
                ),
            ],
            options={
                "verbose_name": "管理授权（业务操作）",
                "verbose_name_plural": "管理授权（业务操作）",
                "db_table": "permissions_operation_grant",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "code"), name="uniq_user_operation"
                    )
                ],
            },
        ),
    ]
