# Generated by Django 5.1.15 on 2026-06-25 07:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_add_fixedasset_model"),
        ("permissions", "0002_seed_grants_from_legacy_role"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="managementscope",
            name="exactly_one_org_node",
        ),
        migrations.AddField(
            model_name="managementscope",
            name="is_all_data",
            field=models.BooleanField(
                default=False,
                help_text="勾选后授权整个组织架构全部数据（含未来新增节点），与具体节点互斥",
                verbose_name="全部数据",
            ),
        ),
        migrations.AddConstraint(
            model_name="managementscope",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("branch__isnull", True),
                        ("is_all_data", True),
                        ("region__isnull", True),
                        ("team__isnull", True),
                    ),
                    models.Q(
                        ("is_all_data", False),
                        models.Q(
                            models.Q(
                                ("branch__isnull", True),
                                ("region__isnull", True),
                                ("team__isnull", False),
                            ),
                            models.Q(
                                ("branch__isnull", False),
                                ("region__isnull", True),
                                ("team__isnull", True),
                            ),
                            models.Q(
                                ("branch__isnull", True),
                                ("region__isnull", False),
                                ("team__isnull", True),
                            ),
                            _connector="OR",
                        ),
                    ),
                    _connector="OR",
                ),
                name="all_data_or_exactly_one_org_node",
            ),
        ),
        migrations.AddConstraint(
            model_name="managementscope",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_all_data", True)),
                fields=("user",),
                name="uniq_user_all_data",
            ),
        ),
    ]
