# Generated by Django 5.1.15 on 2026-08-23 10:05

from django.db import migrations, models


def rename_manage_categories_grants(apps, schema_editor):
    """manage_categories → manage_dictionary（品目字典操作码启用，旧码退役）。

    已持有 manage_dictionary 的用户跳过重命名，避免撞 (user, code) 唯一约束。
    """
    OperationGrant = apps.get_model('permissions', 'OperationGrant')
    has_dictionary = set(
        OperationGrant.objects.filter(code='manage_dictionary').values_list('user_id', flat=True)
    )
    OperationGrant.objects.filter(code='manage_categories').exclude(
        user_id__in=has_dictionary
    ).update(code='manage_dictionary')
    # 剩余的 manage_categories 行均为重复授予，直接清理
    OperationGrant.objects.filter(code='manage_categories').delete()


class Migration(migrations.Migration):

    dependencies = [
        ("permissions", "0003_remove_managementscope_exactly_one_org_node_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operationgrant",
            name="code",
            field=models.CharField(
                choices=[
                    ("manage_users", "管理用户"),
                    ("manage_organizations", "管理组织架构"),
                    ("manage_assets", "管理资产（增删改/导入）"),
                    ("approve_transfer", "审批资产流转"),
                    ("approve_inventory", "审批盘点任务"),
                    ("view_audit", "查看审计日志"),
                    ("view_all_notifications", "查看抄送记录"),
                    ("view_reports", "查看统计报表"),
                    ("manage_dictionary", "管理品目字典"),
                    ("manage_instances", "管理固定资产实例"),
                    ("adjust_ledger", "台账调整单"),
                    ("dispose_assets", "资产处置"),
                ],
                max_length=50,
                verbose_name="业务操作",
            ),
        ),
        migrations.RunPython(rename_manage_categories_grants, migrations.RunPython.noop),
    ]
