# Generated by Django 5.1.15 on 2026-03-31 07:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="分公司名称")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="分公司编码"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="地址"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="联系电话"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "active"), ("inactive", "inactive")],
                        default="active",
                        max_length=10,
                        verbose_name="状态",
                    ),
                ),
            ],
            options={
                "verbose_name": "分公司",
                "verbose_name_plural": "分公司",
                "db_table": "organizations_branch",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="区域名称")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="区域编码"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "active"), ("inactive", "inactive")],
                        default="active",
                        max_length=10,
                        verbose_name="状态",
                    ),
                ),
            ],
            options={
                "verbose_name": "区域",
                "verbose_name_plural": "区域",
                "db_table": "organizations_region",
                "ordering": ["code"],
            },
        ),
    ]
