# Generated by Django 5.1.15 on 2026-03-31 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("organizations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_branches",
                to=settings.AUTH_USER_MODEL,
                verbose_name="分公司负责人",
            ),
        ),
        migrations.AddField(
            model_name="region",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_regions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="区域负责人",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branches",
                to="organizations.region",
                verbose_name="所属区域",
            ),
        ),
    ]
