# Generated by Django 5.1.15 on 2026-04-24 06:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="code",
            field=models.CharField(
                max_length=50,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="编号格式为2-4位大写字母(城市缩写)+3位数字，如 SH001",
                        regex="^[A-Z]{2,4}[0-9]{3}$",
                    )
                ],
                verbose_name="分公司编码",
            ),
        ),
    ]
