# Generated by Django 5.1.15 on 2026-07-30 05:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0004_add_fixedasset_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branches",
                to="organizations.team",
                verbose_name="所属行政组",
            ),
        ),
    ]
