# Generated by Django 5.1.15 on 2026-08-05 08:21

import uuid
from django.db import migrations, models


def seed_company(apps, schema_editor):
    Company = apps.get_model("organizations", "Company")
    Company.objects.get_or_create(name="启航集团")


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0005_branch_team"),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        default="启航集团", max_length=100, verbose_name="集团名称"
                    ),
                ),
            ],
            options={
                "verbose_name": "集团",
                "verbose_name_plural": "集团",
                "db_table": "organizations_company",
            },
        ),
        migrations.RunPython(seed_company, migrations.RunPython.noop),
    ]
