# Generated by Django 5.1.15 on 2026-08-23 12:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0007_branch_team_single_parent"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100, verbose_name="部门名称")),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="departments",
                        to="organizations.branch",
                        verbose_name="所属分公司",
                    ),
                ),
            ],
            options={
                "verbose_name": "部门",
                "verbose_name_plural": "部门字典",
                "db_table": "organizations_department",
                "ordering": ["branch__name", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("branch", "name"), name="uniq_department_branch_name"
                    )
                ],
            },
        ),
    ]
