# Generated by Django 5.1.15 on 2026-09-22 02:34

from django.db import migrations, models


def flatten_departments(apps, schema_editor):
    """部门扁平化回填：同名合并保留最早行，三个 FK 消费表重指向后删重复行。

    纯 Python 聚合（SQLite/PG 双端一致）；幂等——重跑时名称已唯一，dupes 为空自然 no-op。
    """
    Department = apps.get_model("organizations", "Department")
    TransferLine = apps.get_model("transfers", "TransferLine")
    InventoryTask = apps.get_model("inventories", "InventoryTask")
    FixedAsset = apps.get_model("assets", "FixedAsset")

    keep = {}
    dupes = []
    for d in Department.objects.order_by("created_at", "id"):
        if d.name not in keep:
            keep[d.name] = d.id
        else:
            dupes.append(d)
    remap = {d.id: keep[d.name] for d in dupes}

    for old_id, new_id in remap.items():
        TransferLine.objects.filter(department_id=old_id).update(department_id=new_id)
        InventoryTask.objects.filter(department_id=old_id).update(department_id=new_id)
        FixedAsset.objects.filter(department_id=old_id).update(department_id=new_id)
    if dupes:
        Department.objects.filter(id__in=remap).delete()
    print(f"[0009] departments flatten: kept={len(keep)}, merged_away={len(remap)}")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0008_department"),
    ]

    operations = [
        migrations.RunPython(flatten_departments, noop_reverse),
        migrations.AlterModelOptions(
            name="department",
            options={
                "ordering": ["name"],
                "verbose_name": "部门",
                "verbose_name_plural": "部门字典",
            },
        ),
        migrations.RemoveConstraint(
            model_name="department",
            name="uniq_department_branch_name",
        ),
        migrations.RemoveField(
            model_name="department",
            name="branch",
        ),
        migrations.AlterField(
            model_name="department",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="部门名称"
            ),
        ),
    ]
