# Generated by Django 5.1.15 on 2026-03-31 07:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("调拨日期", models.DateField(verbose_name="调拨日期")),
                (
                    "调出分公司",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="调出分公司",
                    ),
                ),
                (
                    "调出部门",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="调出部门"
                    ),
                ),
                (
                    "调入分公司",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="调入分公司",
                    ),
                ),
                (
                    "调入部门",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="调入部门"
                    ),
                ),
                ("资产编号", models.CharField(max_length=100, verbose_name="资产编号")),
                ("资产名称", models.CharField(max_length=200, verbose_name="资产名称")),
                (
                    "规格型号",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="规格型号"
                    ),
                ),
                ("调拨数量", models.IntegerField(default=1, verbose_name="调拨数量")),
                (
                    "调拨原因",
                    models.TextField(blank=True, default="", verbose_name="调拨原因"),
                ),
                (
                    "调出负责人",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="调出负责人",
                    ),
                ),
                (
                    "调入负责人",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="调入负责人",
                    ),
                ),
                ("备注", models.TextField(blank=True, default="", verbose_name="备注")),
                (
                    "审批状态",
                    models.CharField(
                        choices=[
                            ("待审批", "待审批"),
                            ("已通过", "已通过"),
                            ("已驳回", "已驳回"),
                        ],
                        default="待审批",
                        max_length=20,
                        verbose_name="审批状态",
                    ),
                ),
                (
                    "审批人",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="审批人"
                    ),
                ),
                (
                    "审批时间",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="审批时间"
                    ),
                ),
                (
                    "创建人",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="创建人"
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("assign", "领用"),
                            ("return", "归还"),
                            ("transfer", "调拨"),
                            ("repair", "维修"),
                            ("scrap", "报废"),
                        ],
                        default="transfer",
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
            ],
            options={
                "verbose_name": "调拨记录",
                "verbose_name_plural": "调拨记录",
                "db_table": "transfers_transfer",
                "ordering": ["-调拨日期", "-created_at"],
            },
        ),
    ]
