# Generated by Django 5.1.15 on 2026-04-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transfers", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transfer",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("purchase", "采购入库"),
                    ("assign", "领用"),
                    ("return", "归还"),
                    ("transfer", "调拨"),
                    ("repair", "维修"),
                    ("scrap", "报废"),
                ],
                default="transfer",
                max_length=20,
                verbose_name="操作类型",
            ),
        ),
    ]
