# Generated by Django 5.1.15 on 2026-04-16 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0003_team"),
        ("transfers", "0002_add_purchase_action_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfer",
            name="from_branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transfers_from",
                to="organizations.branch",
                verbose_name="调出分公司(FK)",
            ),
        ),
        migrations.AddField(
            model_name="transfer",
            name="to_branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="transfers_to",
                to="organizations.branch",
                verbose_name="调入分公司(FK)",
            ),
        ),
    ]
