# Generated by Django 5.1.15 on 2026-04-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transfers", "0004_populate_branch_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfer",
            name="供应商",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="供应商"
            ),
        ),
        migrations.AddField(
            model_name="transfer",
            name="单价",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="单价",
            ),
        ),
        migrations.AddField(
            model_name="transfer",
            name="总金额",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                verbose_name="总金额",
            ),
        ),
        migrations.AddField(
            model_name="transfer",
            name="用途",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="用途"
            ),
        ),
        migrations.AddField(
            model_name="transfer",
            name="采购经办人",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="采购经办人"
            ),
        ),
        migrations.AddField(
            model_name="transfer",
            name="需求部门",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="需求部门"
            ),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="审批状态",
            field=models.CharField(
                choices=[
                    ("待审批", "待审批"),
                    ("已通过", "已通过"),
                    ("已驳回", "已驳回"),
                    ("已入库", "已入库"),
                ],
                default="待审批",
                max_length=20,
                verbose_name="审批状态",
            ),
        ),
    ]
