# Generated by Django 5.1.15 on 2026-05-21 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "transfers",
            "0005_transfer_供应商_transfer_单价_transfer_总金额_transfer_用途_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="transfer",
            name="出库日期",
            field=models.DateField(blank=True, null=True, verbose_name="出库日期"),
        ),
        migrations.AddField(
            model_name="transfer",
            name="单位",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="单位"
            ),
        ),
        migrations.AddField(
            model_name="transfer",
            name="回收分类",
            field=models.CharField(
                blank=True,
                choices=[
                    ("闲置回收", "闲置回收"),
                    ("报废回收", "报废回收"),
                    ("捐赠回收", "捐赠回收"),
                    ("其他", "其他"),
                ],
                default="",
                max_length=50,
                verbose_name="回收分类",
            ),
        ),
        migrations.AddField(
            model_name="transfer",
            name="存放位置",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="存放位置"
            ),
        ),
        migrations.AddField(
            model_name="transfer",
            name="物品分类",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="物品分类"
            ),
        ),
        migrations.AddField(
            model_name="transfer",
            name="资产类目",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="资产类目"
            ),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("purchase", "采购入库"),
                    ("assign", "领用"),
                    ("return", "归还"),
                    ("transfer", "调拨"),
                    ("recovery", "回收"),
                ],
                default="transfer",
                max_length=20,
                verbose_name="操作类型",
            ),
        ),
    ]
