# Generated by Django 5.1.15 on 2026-06-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transfers", "0006_add_recovery_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transfer",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("purchase", "采购入库"),
                    ("assign", "领用"),
                    ("return", "归还"),
                    ("transfer", "调拨"),
                    ("recovery", "回收"),
                ],
                db_index=True,
                default="transfer",
                max_length=20,
                verbose_name="操作类型",
            ),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="审批状态",
            field=models.CharField(
                choices=[
                    ("待审批", "待审批"),
                    ("已通过", "已通过"),
                    ("已驳回", "已驳回"),
                    ("已入库", "已入库"),
                ],
                db_index=True,
                default="待审批",
                max_length=20,
                verbose_name="审批状态",
            ),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="调拨日期",
            field=models.DateField(db_index=True, verbose_name="调拨日期"),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="资产编号",
            field=models.CharField(
                db_index=True, max_length=100, verbose_name="资产编号"
            ),
        ),
    ]
