# Generated by Django 5.1.15 on 2026-07-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "transfers",
            "0007_alter_transfer_action_type_alter_transfer_审批状态_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="transfer",
            name="审批状态",
            field=models.CharField(
                choices=[
                    ("草稿", "草稿"),
                    ("待审批", "待审批"),
                    ("已通过", "已通过"),
                    ("已驳回", "已驳回"),
                    ("已入库", "已入库"),
                ],
                db_index=True,
                default="待审批",
                max_length=20,
                verbose_name="审批状态",
            ),
        ),
    ]
