# Generated by Django 5.1.15 on 2026-08-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transfers", "0008_alter_transfer_审批状态"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfer",
            name="固定资产内部编号",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="固定资产内部编号"
            ),
        ),
    ]
