# Generated by Django 5.1.15 on 2026-08-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transfers", "0009_transfer_固定资产内部编号"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfer",
            name="回收去向",
            field=models.CharField(
                choices=[("recycle_bin", "入回收库"), ("dispose", "直接处置")],
                default="recycle_bin",
                max_length=20,
                verbose_name="回收去向",
            ),
        ),
        migrations.AddField(
            model_name="transfer",
            name="处置方式",
            field=models.CharField(
                blank=True,
                choices=[("出售", "出售"), ("报废", "报废"), ("捐赠", "捐赠")],
                default="",
                max_length=20,
                verbose_name="处置方式",
            ),
        ),
        migrations.AddField(
            model_name="transfer",
            name="处置金额",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=14,
                null=True,
                verbose_name="处置金额",
            ),
        ),
    ]
