# Generated by Django 5.1.15 on 2026-09-11 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transfers", "0016_drop_line_inner_code_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transfer",
            name="回收去向",
            field=models.CharField(
                choices=[("restock", "重新入库"), ("dispose", "直接处置")],
                default="restock",
                max_length=20,
                verbose_name="回收去向",
            ),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="领用来源",
            field=models.CharField(
                choices=[("stock", "新品库")],
                default="stock",
                max_length=20,
                verbose_name="领用来源",
            ),
        ),
    ]
