# Generated by Django 5.1.15 on 2026-09-21 05:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_created_by(apps, schema_editor):
    """「创建人」字符串 → 账号 FK 回填：唯一命中才填（先姓名后手机号），宁缺勿错。

    只处理 created_by 为空的行（幂等）；重名/无匹配留空——撤回守卫对空 FK 严格拒绝。
    纯 Python 聚合，规避 SQL 方言坑（SQLite/PG 双端一致）。
    """
    Transfer = apps.get_model("transfers", "Transfer")
    User = apps.get_model("users", "User")

    by_name = {}
    by_phone = {}
    for u in User.objects.all():
        by_name.setdefault(u.name, []).append(u.id)
        by_phone.setdefault(u.phone, []).append(u.id)

    filled = skipped_empty = skipped_ambiguous = 0
    for t in Transfer.objects.filter(created_by__isnull=True):
        creator = (t.创建人 or "").strip()
        if not creator:
            skipped_empty += 1
            continue
        candidates = by_name.get(creator) or by_phone.get(creator) or []
        if len(candidates) != 1:
            skipped_ambiguous += 1
            continue
        t.created_by_id = candidates[0]
        t.save(update_fields=["created_by"])
        filled += 1
    print(f"[0020] created_by backfill: filled={filled}, skipped(空创建人)={skipped_empty}, skipped(重名/无匹配)={skipped_ambiguous}")


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("transfers", "0019_transferline_supplier"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="transfer",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_transfers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建账号(FK)",
            ),
        ),
        migrations.RunPython(backfill_created_by, noop_reverse),
        migrations.AlterField(
            model_name="importfingerprint",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="importfingerprint",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="importfingerprint",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
