# Generated by Django 5.1.15 on 2026-09-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transfers", "0024_alter_transfer_经办人"),
    ]

    operations = [
        migrations.AddField(
            model_name="transferlineinstance",
            name="调拨前编号",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="调拨前编号"
            ),
        ),
    ]
