# Generated by Django 5.1.15 on 2026-09-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transfers", "0027_backfill_dispose_spec"),
    ]

    operations = [
        migrations.AddField(
            model_name="transfer",
            name="调入方驳回原因",
            field=models.CharField(
                blank=True, default="", max_length=200, verbose_name="调入方驳回原因"
            ),
        ),
    ]
